### PR TITLE
Add Python 3.7 to Travis CI

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by Mariatta** [comment]
Should we test for both 3.7 and 3.7-dev?

**Comment by webknjaz** [comment]
Depending on your preferences there's also `3.8-dev`/`nightly`. Anything would work.

**Comment by webknjaz** [comment]
@Mariatta I've rebased this PR. Should be safe to merge now.

**Comment by webknjaz** [comment]
@Mariatta ^^

**Comment by Mariatta** [comment]
Thanks!! 🌮

**Comment by webknjaz** [comment]
@Mariatta could you please release a new version of cherry-picker? Some ppl have to work with a version from Git because of missing fixes.

**Comment by webknjaz** [comment]
Hm.. something's wrong. This job shouldn't appear in build: https://travis-ci.org/python/core-workflow/jobs/418766372

**Comment by webknjaz** [comment]
Oh..
```yaml
if: false
```
So it didn't work. it probably needs something more falsy.

**Comment by Mariatta** [comment]
> @Mariatta could you please release a new version of cherry-picker? Some ppl have to work with a version from Git because of missing fixes.

Ok. I was wondering if I should wait for the fix of #277 first or not?

**Comment by Mariatta** [comment]
hmm.. Maybe I should revert this first?

**Comment by webknjaz** [comment]
No, it's probably because of duplicate key and travis' parser "saw" only first one or so. It's probably from previous PR, not this one

**Comment by webknjaz** [comment]
And it's not critical, because there's another check preventing actual deploy. I'll fix if-clause anyway.

**Comment by webknjaz** [comment]
I've raised the issue with Travis, because it looks like their bug: travis-ci/travis-conditions#13.

**Pull request merged**
