### PR TITLE
Move repository sanity check into CherryPicker class.

### PR DESCRIPTION
**Pull request by asvetlov**
Move dry_run printout into CherryPicker constructor as well.

Consider it as a preparation for adding config file #225 
Repository SHA used for CPython repo sanity check should be configurable for using the tool for another repo like aiohttp.
Later we'll do reading the value from config file

### CODE REVIEW

**Comment by Mariatta** [comment]
Thanks for working on this. Do you need this uploaded to PyPI right away?

**Comment by asvetlov** [comment]
No, without config file the change is useless for me.
It is a preparation step only.
I don't want to collect everything into the single PR, which is hard to review and understand all required changes.
Let's keep PRs simple if possible :)

**Comment by Mariatta** [comment]
Awesome. Thanks again!

**Comment by asvetlov** [comment]
:)

**Pull request merged**
