### PR TITLE
Remove `blurb split`; after 3.2 NEWS is generated from next/*, not vice versa

### PR DESCRIPTION
**Pull request by arhadthedev**
The `blurb split` command fixes known historical issues of Misc/NEWS and splits it into Misc/NEWS.d/\*.rst.

However, it lost any use in Python 3.2 when it was replaced with direct committing of Misc/NEWS.d/\*\.*.\*.rst.

So this PR:

- removes this command
- cleans up leftover functions&imports
- replaces verbal mentions of Misc/NEWS with mentions of `Misc/NEWS.d` and `Misc/NEWS.d/next`.

<details><summary>Edit: initially I was way too ambitious and desired to remove blurb merge as well</summary> 

> The blurb tool has two commands that manipulate `Misc/NEWS` file. However, they lost any use in Python 3.2 when it was replaced with direct committing of `Misc/NEWS.d/*.*.*.rst`. These commands are: 
>
> - `blurb merge` (glues new Misc/NEWS.d/\*.rst into old Misc/NEWS)
> - `blurb split` (fixes known historical issues of Misc/NEWS and splits it back into Misc/NEWS.d/*.rst)
> - it was performed last time in https://github.com/python/cpython/commit/260a788767ff6dadd04ecf9e9e26b363ca28c8ae and was never used again
>
>This PR removes these commands, cleans up leftover functions&imports, and replaces verbal mentions of Misc/NEWS with mentions of Misc/NEWS.d or Misc/NEWS.d/next.</details>

### CODE REVIEW

**Comment by hugovk** [comment]
> The blurb tool has two commands that manipulate `Misc/NEWS` file. However, they lost any use in Python 3.2 when it was replaced with direct committing of `Misc/NEWS.d/*.*.*.rst`.

Does that mean we don't need https://github.com/python/cpython/pull/30419 and https://github.com/python/core-workflow/issues/147?

If so, there's a bunch of blurb NEWS stuff that could be removed from https://github.com/python/cpython/blob/main/Doc/Makefile.

**Comment by arhadthedev** [comment]
@hugovk Thank you for noticing! I looked further and found that `blurb merge` is used to generate `NEWS.txt` for Windows distribution. So I reverted this command back.

**Comment by arhadthedev** [comment]
@larryhastings ping

**Comment by arhadthedev** [comment]
@larryhastings Can this PR be merged, please?

**Comment by arhadthedev** [comment]
Erm... ping?

**Review by gpshead — APPROVED** [review]

**Comment by gpshead** [comment]
If for some reason we ever needed this again, that is what we have a version control system for. :)

**Pull request merged**
