### PR TITLE
`textwrap.dedent`, minor PEP8 fixes

### PR DESCRIPTION
**Pull request by delirious-lettuce**
* PEP8: Group imports (standard, third party, local)
* Convert `get_commit_message` to `@staticmethod`
* Fix multi-line fstrings indentation with `textwrap.dedent`
* PEP8: Remove single space from over-indented line
* PEP8: Remove extra blank line above method
* Convert single line fstring to multi-line fstring, use `textwrap.dedent` to fix indentation
* PEP8: Add extra blank line above `cherry_pick_cli` definition
* PEP8: Remove excess space around `=` sign of keyword arg
* PEP8: Add extra space so indentation is multiple of 4

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by Mariatta** [comment]
Thanks for the PR, however I rather not be nitpicky about getting the script to be PEP 8 compliant.

**Comment by delirious-lettuce** [comment]
@Mariatta ,

> A style guide is about consistency. Consistency with this style guide is important. Consistency within a project is more important. ***Consistency within one module or function is the most important.***

* I didn't break backwards compatibility with this PR.
* The changes made improve the readability of the script
* The changes made improve the consistency of the script
* `cherry_picker.py` does not predate PEP8

It just seems odd that you wouldn't want code in the actual Python repository to adhere to normal Python practices.

**Comment by larryhastings** [comment]
https://www.youtube.com/watch?v=wf-BqAjZb8M

**Comment by delirious-lettuce** [comment]
@larryhastings & @Mariatta ,

> ["I mostly love PEP8, I think it's extremely well-written. I also think that right at the top where it says a foolish consistency is the hobgoblin of little minds, people skip right past that part." - 6:25](https://youtu.be/wf-BqAjZb8M?t=384)

Feel free to refer to my previous comment. Not only is the quote from that exact section, the points listed also correspond to the suggestions made by that exact section.

> ["Also, there was some weird indentation in here and inconsistent. Python allows that but now that everything lines up better, I think the logic of this is more transparent." - 20:22](https://youtu.be/wf-BqAjZb8M?t=1222)

The main point of my PR was to use `textwrap.dedent` for the multi-line fstrings. Neither one of you have explained why using `textwrap.dedent` would be detrimental to this script.

When I then noticed more inconsistent indentation (theme of the PR), I fixed those instances as well.

> ["One of Guido's key insights is that code is read much more often than it is written."](https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds)

---
PS - Good luck on the Gilectomy, @larryhastings !

**Comment by brettcannon** [comment]
I have locked down this conversation as it is no longer productive. While updating surrounding code to fix minor things like indentation during a bugfix is fine, updating code just to change its style is generally frowned upon as it generates needless noise in the commit history.

**Pull request closed without merging**
