### PR TITLE
Move cherry_picker to flit

### LINKED ISSUE #140: Move cherry_picker over to flit
It's just so much easier to work with than setuptools for projects like cherry_picker that are just pure Python.

### PR DESCRIPTION
**Pull request by brettcannon**
Closes #140

### CODE REVIEW

**Comment by brettcannon** [comment]
@Mariatta sorry I didn't recommend this to begin with (I just didn't know)! Much simpler than setuptools.

**Comment by willingc** [comment]
@mariatta Just an FYI for the future that flit is maintained by Jupyter's very wonderful @takluyver. Thanks Thomas too :smile:

**Comment by brettcannon** [comment]
@willingc knowing @takluyver is the maintainer is the entire reason I'm willing to trust flit. 😄

**Comment by takluyver** [comment]
Thanks for the kind words!

**Pull request merged**
