### PR TITLE
(don't merge) Add --abort/--continue option to cherry_picker.py

### PR DESCRIPTION
**Pull request by Mariatta**
`--abort`
Do `git cherry-pick --abort`
Clean up branch

`--continue`
Do `git commit -am "resolved" --allow-empty`
Clean up branch

demo: https://asciinema.org/a/dfalzy45oq8b3c6dvakwfs6la

Closes https://github.com/python/core-workflow/issues/45

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
I meant something different. I want the behavior similar to `git cherry-pick --continue/--abort`. `python -m cherry_picker --continue` should continue the work after the failure of previous run of cherry_picker. For example after manually fixing the conflicts it should push the branch and open a PR. `python -m cherry_picker --abort` should reset unfinished cherry-picking (run `git cherry-pick --abort`, remove the branch, etc).

**Comment by Mariatta** [comment]
Ok I think this is what you wanted:

1. run `python -m cherry_picker <hash> <branch> <branch>`
2. if it failed in `<branch 1>`,  stop. 

From here user has 2 options:

option 1:
1. manually fix it
2. run `python -m cherry_picker --continue` 
3. cherry_picker.py will push and open the PR
4. cherry_picker.py will clean up the branch

option 2:
1. run `python -m cherry_picker --abort`
2. this will run git cherry-pick --abort
3. cherry_picker.py will clean up the branch

 :thinking: Sounds right?

**Comment by serhiy-storchaka** [comment]
Yes, it is what I meant. Thank you for explaining it.

**Comment by Mariatta** [comment]
@serhiy-storchaka I implemented the behavior as discussed above.
Demo https://asciinema.org/a/dfalzy45oq8b3c6dvakwfs6la

**Comment by ncoghlan** [comment]
@Mariatta Given #68, should this be closed now?

**Pull request closed without merging**
