### PR TITLE
blurb: support Python 3.10, drop EOL 3.6, and fix README badges

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
@hugovk if no one else reviews this after a week, ping me and I will merge it.

**Comment by hugovk** [comment]
@brettcannon One week ping!

**Review by sobolevn — APPROVED** [review]
Just wanted to do the same thing! Thanks, @hugovk!

**Comment by arhadthedev** [comment]
> if no one else reviews this after a week, ping me and I will merge it.

> One week ping!

@brettcannon (to see updated README in alpha 5 the nearest Tuesday)

**Pull request merged**
